### PR TITLE
Update runtime to 24.08

### PR DESCRIPTION
**Pull request by guihkx**

### CODE REVIEW

**Comment by guihkx** [comment]
It's really late for me right now, so I'll take a better look at the build failure tomorrow.

**Comment by ilya-fedin** [comment]
It just needs the tdesktop update to get published on the repo. After that it should build just fine.

**Comment by ilya-fedin** [comment]
This time the error seem to be real. Sadly I have no idea what to do with that. Thoughts?

**Comment by AsciiWolf** [comment]
The error seems to be caused by appstream-compose missing in the 24.08 runtime. This Flatpak should switch to using `appstreamcli`. See [this ticket](https://github.com/flathub/com.obsproject.Studio.Plugin.GStreamerVaapi/issues/30).

**Comment by AsciiWolf** [comment]
https://www.freedesktop.org/software/appstream/docs/re02.html

**Pull request merged**
